### ISSUE TITLE
Update spirv_headers to 1.4.1

### ISSUE THREAD

**Issue by malobre** [gwihlidal/spirv-reflect-rs#10]
Please consider using version 1.4.1 of spirv_headers.
They removed `num_derive` which depends on `syn` (slow build).
This would optimize your build time and help other crates depending on this (see https://github.com/amethyst/rendy/issues/203).

**Comment by malobre** [comment]
Bump @gwihlidal

**Comment by gwihlidal** [comment]
Hi @malobre - it appears that v1.4.1 has been yanked from crates.io

**Comment by malobre** [comment]
Yeah, seems like they are having some difficulties. In that case I'll reopen my PR.
